//{{NO_DEPENDENCIES}}
// Microsoft eMbedded Visual C++ generated include file.
// Used by zsIRC.rc
//
#define IDD_ABOUTBOX                    100
#define IDS_EDIT                        102
#define IDS_TOOL                        103
#define IDM_MENU                        104
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAIN_EDIT                   105
#define IDR_MAIN_TOOL                   106
#define IDD_ABOUTBOX1                   109
#define IDR_MAINFRAME                   128
#define IDR_TOOLBAR1                    134
#define IDR_EDIT                        137
#define IDR_CBAR                        138
#define IDR_USER                        139
#define IDB_BITMAP1                     140
#define IDI_NOTIFYICON                  143
#define IDD_OPTIONS                     144
#define IDD_OPTIONS_CONNECTION          145
#define IDR_OPTIONS                     146
#define IDD_OPTIONS_APPEARANCE          147
#define IDD_OPTIONS_BEHAVIOUR           148
#define IDD_OPTIONS_LOGGING             149
#define IDD_OPTIONS_FONTS               150
#define IDD_OPTIONS_COLORS              151
#define IDD_OPTIONS_NICKS               152
#define IDR_SOFTKEYTEST                 153
#define IDC_BUTTON2                     1002
#define IDC_APPLY                       1002
#define IDC_BUILD                       1003
#define IDC_TAB1                        1004
#define IDC_SERVER_NAME                 1005
#define IDC_SERVER_PORT                 1006
#define IDC_SERVER_PASS                 1007
#define IDC_TIMESTAMPS                  1007
#define IDC_IDENT                       1008
#define IDC_NICKLISTWIDTH               1008
#define IDC_REALNAME                    1009
#define IDC_CHANNELBARHEIGHT            1009
#define IDC_REALNAME2                   1010
#define IDC_QUITMESSAGE                 1010
#define IDC_SORTCHANNELS                1010
#define IDC_REALNAME3                   1011
#define IDC_AUTOCONNECT                 1011
#define IDC_REJOINONCONNECT             1012
#define IDC_PASSCOMMANDSRAW             1013
#define IDC_CODEPAGE                    1014
#define IDC_STRIPCOLORCODES             1015
#define IDC_LOGGING                     1015
#define IDC_OFFSCREENBUFFERING          1016
#define IDC_DOLOGTIMESTAMP              1016
#define IDC_SORTCHANNELS2               1016
#define IDC_CHECKFORUPDATES             1016
#define IDC_LOGDIRECTORY                1017
#define IDC_CONVERSATIONFONT            1018
#define IDC_CONVERSATIONFONTSIZE        1019
#define IDC_BUTTONFONT                  1020
#define IDC_BUTTONFONTSIZE              1021
#define IDC_NICKLISTFONT                1022
#define IDC_NICKLISTFONTSIZE            1023
#define IDC_FOREGROUNDCOLOR             1023
#define IDC_BACKGROUNDCOLOR             1024
#define IDC_ACTIONCOLOR                 1025
#define IDC_JOINCOLOR                   1026
#define IDC_MODECOLOR                   1027
#define IDC_NICK0                       1027
#define IDC_PARTCOLOR                   1028
#define IDC_NICK1                       1028
#define IDC_SERVER_SECURE               1028
#define IDC_NOTICECOLOR                 1029
#define IDC_NICK2                       1029
#define IDC_SSL_INVALID                 1029
#define IDC_NICK3                       1030
#define IDC_NICK4                       1031
#define IDC_NICK5                       1032
#define IDC_NICK6                       1033
#define IDC_NICK7                       1034
#define IDC_NICK8                       1035
#define IDC_NICK9                       1036
#define ID_MENU1                        32771
#define IDS_CAP_MENU                    32773
#define ID_EXIT                         32774
#define ID_BUTTON32776                  32776
#define ID_MENU_CONNECT                 32777
#define ID_EDIT_ROOT                    32778
#define IDS_CAP_ROOT                    32780
#define IDR_CBAR_ROOT                   32781
#define IDR_CBAR_CLOSE                  32783
#define IDR_USER_ROOT                   32784
#define IDR_USER_QUERY                  32786
#define ID_MENU_ABOUT                   32787
#define IDR_USER_WHOIS                  32788
#define ID_MENU_CHECK                   32789
#define ID_MENU_VISIT                   32790
#define IDR_USER_WHOISEX                32791
#define ID_MENU_OPTIONS                 32792
#define ID_OPTIONS_OK                   32793
#define IDS_CAP_OK                      32795
#define ID_OPTIONS_CANCEL               32796
#define IDS_CAP_CANCEL                  32798
#define IDS_CAP_MENUITEM32800           32801
#define ID_MENU_NEXTCHAN                32802
#define IDS_CAP_NEXTCHAN                32804
#define ID_1                            32805
#define IDS_CAP_1                       32807
#define ID_2                            32808
#define IDS_CAP_2                       32810
#define ID_3                            32811
#define IDS_CAP_3                       32813
#define ID_2_TEST                       32814
#define ID_1_PUU                        32815
#define ID_3_TEEEEST                    32816
#define ID_OPTIONS_MENU                 32820
#define ID_OPTIONS_APPLY                32821
#define ID_MENU_NEWSERVER               32822
#define IDS_NEW                         65000
#define IDS_FILE                        65001
#define IDS_MHELP                       65002
#define IDS_SAVE                        65003
#define IDS_CUT                         65004
#define IDS_COPY                        65005
#define IDS_PASTE                       65006
#define IDS_ABOUT                       65007

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        154
#define _APS_NEXT_COMMAND_VALUE         32823
#define _APS_NEXT_CONTROL_VALUE         1030
#define _APS_NEXT_SYMED_VALUE           111
#endif
#endif
